### ISSUE TITLE
The demo site is not working

### ISSUE THREAD

**Issue by andrewtimberlake** [PoslinskiNet/ember-pell#23]
I wanted to look into this addon but the demo application just shows a loading animation with errors in the console.

**Comment by PoslinskiNet** [comment]
I've just tested it and it seems to work OK. @andrewtimberlake Could you verify it?

**Comment by andrewtimberlake** [comment]
Nope, still not working—Safari

**Comment by PoslinskiNet** [comment]
I've just tested on Safari as well - at 11.0.3 it seems to work. @andrewtimberlake Could you send some console error log? 

<img width="1432" alt="zrzut ekranu 2018-03-13 o 22 56 05" src="https://user-images.githubusercontent.com/1891508/37372073-d3b8c64e-2711-11e8-87ac-6fc6f09d693c.png">

**Comment by andrewtimberlake** [comment]
One of the errors seemed to point to my Github login so I logged off and on again and it is now working, thanks.
![Have you turned it off and on again](https://media1.tenor.com/images/d02accbfb6e715dc99072f375509dc81/tenor.gif?itemid=4770974)
