### ISSUE TITLE
Add a reference to the original library in the README

### ISSUE THREAD

**Issue by jaredreich** [PoslinskiNet/ember-pell#25]
https://github.com/jaredreich/pell

**Comment by PoslinskiNet** [comment]
Actually, there was one already (at the bottom, as a reference/license related section. However, I've added another one in the main description:
https://github.com/PoslinskiNet/ember-pell/commit/2f61ae26339240ea10d6f38ef9527c029956b0d9

Thanks for your great work!

**Comment by jaredreich** [comment]
😄
