### ISSUE TITLE
pell-editor is not a helper

### ISSUE THREAD

**Issue by mikejerome** [PoslinskiNet/ember-pell#30]
When I try to use this on my Ember 3.0 app I get the error 'pell-editor is not a helper'.

**Comment by PoslinskiNet** [comment]
I did some quick test @mikejerome and it seems to work fine.

<img width="979" alt="zrzut ekranu 2018-05-06 o 19 25 04" src="https://user-images.githubusercontent.com/1891508/39676014-5e32ff76-5163-11e8-815c-65be1e093c17.png">

Maybe you need to clean up caches to make sure that addon is properly installed?

**Comment by mikejerome** [comment]
Hmmm I just deleted node_modules and reinstalled ember-pell but I keep getting the same error.

**Comment by PoslinskiNet** [comment]
Could you provide your `package.json` @mikejerome - I think it may be somehow related with a versions of the packages

**Comment by wayne-o** [comment]
I'm getting the same

**Comment by elgordino** [comment]
This looks to be a compatibility issue with the 'pods' layout of an ember project. It works fine in a regular ember project but it fails as soon as `usePods: true` is set in `.ember-cli`

I have created a reproduction here: https://github.com/elgordino/ember-pell-pods

This was created with 

```
$ ember --version                                                                                                                                 *[master] 
ember-cli: 2.18.2
node: 8.9.0
os: darwin x64
$ ember new ember-pell-pods      
$ ember install ember-pell
```

Adding `pell-editor` in `templates/application.hbs` works fine. But then converting to pods and moving the file to `features/application/template.hbs` results in `pell-editor is not a helper`

**Comment by PoslinskiNet** [comment]
@elgordino thanks for the reproduction! I will try to figure it out how to handle it for pods use-case.

**Comment by elgordino** [comment]
Thanks @PoslinskiNet I tried to have a dig into it myself but wasn't able to make much headway, I hope you have luck!

**Comment by elgordino** [comment]
Works perfectly @PoslinskiNet thanks a ton for this!
