### ISSUE TITLE
'undefined' value

### ISSUE THREAD

**Issue by lougreenwood** [PoslinskiNet/ember-pell#34]
I'm using ember-pell in a form backed by ember-changeset

I've noticed that when ember-pell is initialised and no value is set for the field (i.e new empty form), then the form contains the value 'undefined'

Seems that the problem is here:

https://github.com/PoslinskiNet/ember-pell/blob/master/addon/components/pell-editor.js#L34

PR incoming...

**Comment by mnoble01** [comment]
I'm seeing this same behavior in IE9 when the value is "null"
