### ISSUE TITLE
Prevent HTML tags addition

### ISSUE THREAD

**Issue by Kerhael** [PoslinskiNet/ember-pell#51]
Hi, 

I am trying to use pell editor with ember JS. It is working quite fine except for one issue I am not able to solve :(.

Here is my controller:
```
this.pellOptions = {
      defaultParagraphSeparator: 'p',
      styleWithCSS: false,
}
```

Here is the template:
`{{pell-editor value=model.text onChange=(action (mut model.text)) pellOptions=pellOptions}}`

Here is what I expect as a result:
```
<div>
    <p><span style="font-weight: bold;">Type: </span> exploration, adventure</p>
    <br>
    <p><span style="font-weight: bold;">Audio: </span> English</p>
</div>
```

But here is what I get:
```
<div>
	<p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:0pt;\">
		<span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">
			Type :
		</span>
		<span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> 
			exploration, adventure
		</span>
	</p>
	<p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:0pt;\">
		<b style=\"font-weight:normal;\" id=\"docs-internal-guid-3043454b-7fff-1bb3-5342-d483cd8e3215\">
			<br>
		</b>
	</p>
	<p dir=\"ltr\" style=\"line-height:1.38;margin-top:0pt;margin-bottom:0pt;\">
		<span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\">
			Audio :
		</span>
		<span style=\"font-size:11pt;font-family:Arial;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;\"> 
			English
		</span>
	</p>
</div>
<style type=\"text/css\"><!--td {border: 1px solid #ccc;}br {mso-data-placement:same-cell;}--></style>
```

Lots of useless code has been added. Is it possible to get rid of it in one way or another?

Thanks in advance

**Comment by PoslinskiNet** [comment]
@Kerhael I think there might be some extra code involved that add some extra stuff there. I've created a [twiddle](https://ember-twiddle.com/03d0e7715565eefb414127bce41768e2?openFiles=templates.application.hbs%2C) based on what you've provided in the issue.

And it seems to work ok. Maybe there is something missing in reproduction scenario that may help find the issue?

**Comment by Kerhael** [comment]
Hi Dawid,

You're right, I think extra code might come from copy-paste: the text I pasted in pell editor was copied from a google doc. I guess it came with google doc's own hidden extra code and styling.

Is there any way of cleaning the code before (or after) pasting?

My coworker is going to have to paste 600 small texts like that from a google doc to the pell editor and it would be so much better for him if he had not to paste it in a code editor first then in pell editor then do the styling again.

**Comment by PoslinskiNet** [comment]
@Kerhael The easiest way at the moment I can see is to paste without styling which is available in most browsers if you use instead of `cmd+v` (on Mac) / `ctrl+v` - `shift+cmd+v` (on Mac) / `shit+ctrl+v`... maybe that could be good enough in your case?

It is the way how browser stores the data from when you copy it from the Google Docs. With this shortcut, you can strip it easily.

**Comment by Kerhael** [comment]
@PoslinskiNet yes I think we're gonna have to paste without styling like you said.
Not a pell issue then, I'll close this.
Thanks for your help and have a nice day!
