### ISSUE TITLE
BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNodes[0]

### ISSUE THREAD

**Issue by kangks** [PoslinskiNet/ember-pell#6]
Rolled back to 1.0.0 resolve the issue.

**Comment by PoslinskiNet** [comment]
Could you provide more details @kangks and/or Ember twiddle so I can reproduce it and prepare a fix for this?

**Comment by nielsrask** [comment]
Got the exact same thing. And resolved the same way.

**Comment by dimitrivdp** [comment]
I also had the issue. Rolling back to 1.0.0 resolves the problem.

I'm an ember Newbe... so tell me how I can help you solve this issue.

**Comment by nielsrask** [comment]
It sounds like you already solved it. If you want to revert to that version you can just insert this command and it should work:

npm install ember-pell@1.0.0 --save-dev

**Comment by mukk85** [comment]
Also found this issue with 1.1.0
